version: '3'
services:
  mysql:
    image: mysql:latest
    networks:
      - coupon_network
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=coupon

  redis:
    image: redis:latest
    networks:
      - coupon_network
    ports:
      - '6379:6379'

networks:
  coupon_network:
    driver: bridge